{application,sage,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"Sagas pattern implementation for distributed or long lived transactions and their error handling."},
              {modules,['Elixir.Inspect.Sage','Elixir.Sage',
                        'Elixir.Sage.AsyncTransactionTimeoutError',
                        'Elixir.Sage.CompensationErrorHandler',
                        'Elixir.Sage.DuplicateFinalHookError',
                        'Elixir.Sage.DuplicateStageError',
                        'Elixir.Sage.DuplicateTracerError',
                        'Elixir.Sage.EmptyError','Elixir.Sage.Executor',
                        'Elixir.Sage.Executor.Retries',
                        'Elixir.Sage.MalformedCompensationReturnError',
                        'Elixir.Sage.MalformedTransactionReturnError',
                        'Elixir.Sage.Tracer']},
              {registered,[]},
              {vsn,"0.6.1"},
              {mod,{'Elixir.Sage',[]}}]}.
